//go:build !ignore_autogenerated

/*
Copyright 2026 Ben.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoDiscoverySpec) DeepCopyInto(out *AutoDiscoverySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoDiscoverySpec.
func (in *AutoDiscoverySpec) DeepCopy() *AutoDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(AutoDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPMonitorOptions) DeepCopyInto(out *HTTPMonitorOptions) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AcceptedStatusCodes != nil {
		in, out := &in.AcceptedStatusCodes, &out.AcceptedStatusCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPMonitorOptions.
func (in *HTTPMonitorOptions) DeepCopy() *HTTPMonitorOptions {
	if in == nil {
		return nil
	}
	out := new(HTTPMonitorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorTag) DeepCopyInto(out *MonitorTag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorTag.
func (in *MonitorTag) DeepCopy() *MonitorTag {
	if in == nil {
		return nil
	}
	out := new(MonitorTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaConfig) DeepCopyInto(out *UptimeKumaConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaConfig.
func (in *UptimeKumaConfig) DeepCopy() *UptimeKumaConfig {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UptimeKumaConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaConfigList) DeepCopyInto(out *UptimeKumaConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UptimeKumaConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaConfigList.
func (in *UptimeKumaConfigList) DeepCopy() *UptimeKumaConfigList {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UptimeKumaConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaConfigSpec) DeepCopyInto(out *UptimeKumaConfigSpec) {
	*out = *in
	out.APIKeySecret = in.APIKeySecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaConfigSpec.
func (in *UptimeKumaConfigSpec) DeepCopy() *UptimeKumaConfigSpec {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaConfigStatus) DeepCopyInto(out *UptimeKumaConfigStatus) {
	*out = *in
	if in.LastConnectionTime != nil {
		in, out := &in.LastConnectionTime, &out.LastConnectionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaConfigStatus.
func (in *UptimeKumaConfigStatus) DeepCopy() *UptimeKumaConfigStatus {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaGroup) DeepCopyInto(out *UptimeKumaGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaGroup.
func (in *UptimeKumaGroup) DeepCopy() *UptimeKumaGroup {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UptimeKumaGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaGroupList) DeepCopyInto(out *UptimeKumaGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UptimeKumaGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaGroupList.
func (in *UptimeKumaGroupList) DeepCopy() *UptimeKumaGroupList {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UptimeKumaGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaGroupSpec) DeepCopyInto(out *UptimeKumaGroupSpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaGroupSpec.
func (in *UptimeKumaGroupSpec) DeepCopy() *UptimeKumaGroupSpec {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaGroupStatus) DeepCopyInto(out *UptimeKumaGroupStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaGroupStatus.
func (in *UptimeKumaGroupStatus) DeepCopy() *UptimeKumaGroupStatus {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaMonitor) DeepCopyInto(out *UptimeKumaMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaMonitor.
func (in *UptimeKumaMonitor) DeepCopy() *UptimeKumaMonitor {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UptimeKumaMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaMonitorList) DeepCopyInto(out *UptimeKumaMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UptimeKumaMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaMonitorList.
func (in *UptimeKumaMonitorList) DeepCopy() *UptimeKumaMonitorList {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UptimeKumaMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaMonitorSpec) DeepCopyInto(out *UptimeKumaMonitorSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]MonitorTag, len(*in))
		copy(*out, *in)
	}
	if in.AutoDiscovery != nil {
		in, out := &in.AutoDiscovery, &out.AutoDiscovery
		*out = new(AutoDiscoverySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPMonitorOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaMonitorSpec.
func (in *UptimeKumaMonitorSpec) DeepCopy() *UptimeKumaMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeKumaMonitorStatus) DeepCopyInto(out *UptimeKumaMonitorStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UptimeStats != nil {
		in, out := &in.UptimeStats, &out.UptimeStats
		*out = new(UptimeStats)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeKumaMonitorStatus.
func (in *UptimeKumaMonitorStatus) DeepCopy() *UptimeKumaMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(UptimeKumaMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeStats) DeepCopyInto(out *UptimeStats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeStats.
func (in *UptimeStats) DeepCopy() *UptimeStats {
	if in == nil {
		return nil
	}
	out := new(UptimeStats)
	in.DeepCopyInto(out)
	return out
}
